FROM nvcr.io/nvidia/pytorch:21.06-py3

ARG USERNAME=root
ARG PASSWORD

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
	sudo \
	rsync \
	lftp \
	libgl1-mesa-glx \
	libglib2.0

RUN if [ $USERNAME != 'root' ]; then \
		useradd -m ${USERNAME} -p $(openssl passwd -1 ${PASSWORD}); \
	fi
USER ${USERNAME}

RUN mkdir ~/.lftp
RUN echo "set ssl:verify-certificate no" >> ~/.lftp/rc

COPY install.sh /workspace

RUN bash install.sh && rm install.sh
